---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: fluffy
spec:
  owner: chun-tech
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fluffy
  annotations:
    github.com/project-slug: wtnb-yk/fluffy
spec:
  type: web-site
  lifecycle: experimental
  owner: chun-tech
  system: fluffy
  providesApis:
    - fluffy-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: fluffy-api
spec:
  type: openapi
  lifecycle: experimental
  owner: chun-tech
  system: fluffy
  definition: |
    openapi: "3.1.0"
    info:
      version: 1.0.0
      title: fluffy API
    paths: 
      targetDir: ./fluffy-api-spec/fluffy-api.yml
