---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: fluffy
spec:
  owner: chun-tech
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fluffy
  annotations:
    github.com/project-slug: wtnb-yk/fluffy
spec:
  type: web-site
  lifecycle: experimental
  owner: chun-tech
  system: fluffy

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: fluffy-api
spec:
  type: openapi
  lifecycle: experimental
  owner: chun-tech
  system: fluffy
  definition: |
    $text: https://petstore.swagger.io/v2/swagger.json
