apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fluffy-web
  annotations:
    github.com/project-slug: wtnb-yk/fluffy
spec:
  type: web-site
  lifecycle: experimental
  system: fluffy
  owner: wtnb-yk

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: fluffy-api
  description: fluffy-api
spec:
  type: openapi
  lifecycle: experimental
  owner: wtnb-yk
  system: fluffy
  definition: |
