apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fluffy
  annotations:
    github.com/project-slug: wtnb-yk/fluffy
spec:
  type: other
  lifecycle: unknown
  owner: wtnb-yk
  system: fluffy

apiVersion: backstage.io/v1alpha1
  kind: API
  metadata:
    name: fluffy-api
    description: fluffy-api
  spec:
    type: openapi
    lifecycle: experimental
    owner: wtnb-yk
    system: fluffy
