apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fluffy
  annotations:
    github.com/project-slug: wtnb-yk/fluffy
spec:
  type: service
  lifecycle: experimental
  owner: chun-tech
  system: fluffy

kind: API
metadata:
  name: fluffy-api
  description: fluffy-api
spec:
  type: openapi
  lifecycle: experimental
  owner: chun-tech
  system: fluffy
