version: "3"
services:
  api:
    image: <イメージ名>
    container_name: <コンテナ名>
    networks:
      - <ネットワーク名>
    volumes:
      - <ボリューム名>
    ports:
      - <ポート番号>
    environment:
      <キー1>: <バリュー1>
      <キー2>: <バリュー2>
    depends_on:
      - <依存関係にあるサービス>
    restart: <コンテナ停止時の対応>
    command: <実行するコマンド>
networks:
  ネットワーク名1:
volumes:
  ボリューム名1:
