# 共通
spring:
  datasource:
    url: jdbc:postgresql://${DB_MASTER_HOST:localhost}:${DB_MASTER_PORT:10232}/${DB_NAME:facility-store}
    username: ${DB_USER:docker}
    password: ${DB_PASS:docker}
    driver-class-name: org.postgresql.Driver
  profiles:
    default: localhost

---

######################
# Profile: localhost #
######################

spring:
  config:
    activate:
      on-profile: localhost
  devtools:
    restart:
      enabled: true

server:
  port: 10280

logging:
  level:
    org.springframework.web: DEBUG
    org.jooq.tools.LoggerListener: DEBUG
    org.springframework.security: DEBUG
    root: INFO
  config: classpath:log4j2-local.xml

#custom:
#  env: localhost
#  allowed-origins:

---

###################
# Profile: remote #
###################

spring:
  config:
    activate:
      on-profile: remote

server:
  port: 8080

logging:
  level:
    root: INFO
  config: classpath:log4j2-remote.xml

#custom:
#  env: ${ENV}
#  allowed-origins: ${ALLOWED_ORIGINS}
