openapi: 3.0.0
info:
  version: 1.0.0
  title: Fluffy API
  description: fluffy-api
servers:
  - url: ''
paths:
  /ping:
    get:
      summary: ヘルスチェック用エンドポイント
      operationId: healthCheck
      tags:
        - system
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: ping