openapi: 3.0.0
info:
  version: 1.0.0
  title: Fluffy API
  description: fluffy-api
servers:
  - url: 'https://localhost:10280/fluffy-api/'
paths:
  /ping:
    get:
      summary: ヘルスチェック用エンドポイント
      operationId: healthCheck
      tags:
        - system
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: ping
  /me:
    get:
      summary: 自分自身の情報を取得
      tags:
        - me
      operationId: getMe
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Me'

components:
  schemas:
    Me:
      title: Me
      type: object
      properties:
        userId:
          type: string
          format: UUID
        userName:
          type: string
      required:
        - userId
        - userName